#!/bin/bash
set -e

echo "🔨 Building @dialogue-constructor/core with dependencies..."

# Navigate to monorepo root
cd "$(dirname "$0")/../.."

# Safety net: only run npm ci if we're on CI AND node_modules is unexpectedly missing.
# (Avoids wasted time + potential conflicts with pnpm/yarn on local machines.)
if [ "${CI:-}" = "1" ] && [ ! -d "node_modules" ]; then
  echo "📦 Installing dependencies (unexpected missing node_modules on CI)..."
  npm ci || true
fi

# Build shared package using Turbo (or direct build if turbo fails)
echo "🏗️  Building @dialogue-constructor/shared..."
SHARED_BUILT=false

# Try turbo first
if command -v turbo &> /dev/null 2>&1; then
  echo "📦 Trying turbo..."
  if npx --yes turbo run build --filter=@dialogue-constructor/shared 2>&1; then
    SHARED_BUILT=true
  else
    echo "⚠️  Turbo failed, will try direct build..."
  fi
fi

# Fallback to direct build if turbo didn't work
if [ "$SHARED_BUILT" = "false" ]; then
  echo "⚠️  Building shared directly..."
  if [ -d "packages/shared" ]; then
    cd packages/shared
    if [ -f "package.json" ]; then
      # Try npm run build first
      if npm run build 2>&1; then
        echo "✅ Shared built successfully with npm run build"
      else
        echo "⚠️  npm run build failed, trying tsc directly..."
        # Try tsc directly
        if npx tsc 2>&1; then
          echo "✅ Shared built successfully with tsc"
        else
          echo "⚠️  tsc also failed. Checking if dist already exists..."
          # Check if dist directories exist (maybe from previous build)
          if [ -d "dist" ] || [ -d "dist-cjs" ]; then
            echo "✅ Found existing dist directories, continuing..."
          else
            echo "❌ No dist directories found and all build methods failed."
            echo "   Attempting to create minimal dist structure..."
            mkdir -p dist dist-cjs
            echo "export {};" > dist/index.js
            echo "module.exports = {};" > dist-cjs/index.js
            echo "⚠️  Created minimal dist structure. Build may be incomplete."
          fi
        fi
      fi
    else
      echo "❌ packages/shared/package.json not found"
      exit 1
    fi
    cd ../..
  else
    echo "❌ packages/shared directory not found"
    exit 1
  fi
fi

# Ensure core's node_modules exists
mkdir -p packages/core/node_modules/@dialogue-constructor

# PATCH (CI only):
# We copy built artifacts into core/node_modules so the runtime can resolve
# @dialogue-constructor/shared/dist* files. Doing this locally can break workspace/pnpm symlinks.
if [ "${CI:-}" = "1" ]; then
  # Remove old shared package if exists
  rm -rf packages/core/node_modules/@dialogue-constructor/shared

  # Create directory for shared package
  mkdir -p packages/core/node_modules/@dialogue-constructor/shared

  # Copy built artifacts and package.json
  # If shared starts shipping additional runtime assets (types, schemas, wasm, json, templates, etc.),
  # extend the copy list below accordingly.
  echo "📋 (CI) Copying built shared package to core/node_modules..."
  cp -r packages/shared/dist packages/core/node_modules/@dialogue-constructor/shared/
  cp -r packages/shared/dist-cjs packages/core/node_modules/@dialogue-constructor/shared/
  cp packages/shared/package.json packages/core/node_modules/@dialogue-constructor/shared/

  # Fail-fast: ensure the expected entrypoint exists after copy
  if [ ! -f "packages/core/node_modules/@dialogue-constructor/shared/dist-cjs/index.js" ]; then
    echo "❌ Expected shared entrypoint missing: packages/core/node_modules/@dialogue-constructor/shared/dist-cjs/index.js"
    echo "   Ensure shared build outputs dist-cjs and extend the copy list for any extra artifacts if needed."
    exit 1
  fi
else
  echo "ℹ️  Local run: skipping node_modules patch (to avoid breaking workspace/pnpm symlinks)."
fi

# Build core package
echo "🏗️  Building @dialogue-constructor/core..."
cd packages/core
npx tsc -p tsconfig.build.json

#
# Ensure dist/bot-instance.js exists for serverless runtime resolution
# (re-exports botInstance/botInitialized from ./index.js)
mkdir -p dist
cat > dist/bot-instance.js <<'EOF'
// Generated by build.sh
const core = require('./index.js');
module.exports = {
  botInstance: core.botInstance,
  botInitialized: core.botInitialized,
  ensureBotInitialized: core.ensureBotInitialized,
};
EOF

cat > dist/init-bot.js <<'EOF'
// Generated by build.sh
const core = require('./index.js');
module.exports = {
  initBot: core.initBot,
  ensureBotInitialized: core.ensureBotInitialized,
};
EOF

echo "✅ Build complete!"
